INSERT INTO USERS (USER_ID,NAMEUSER,SURNAME,AGE,EMAIL,INIT_DATE) 
VALUES ('5','Maria','Lopez','67','maria@gmail.com',SYSDATE)


INSERT INTO USERS (NAMEUSER,SURNAME,AGE,EMAIL,INIT_DATE) 
VALUES ('Sandia','Melocoton','17','sandimelo@gmail.com',SYSDATE)