SELECT MAX(AGE) FROM USERS GROUP BY AGE;

SELECT COUNT(AGE), AGE FROM USERS GROUP BY AGE;

SELECT COUNT(AGE), AGE FROM USERS GROUP BY AGE ORDER BY AGE ASC;

SELECT COUNT(AGE), AGE FROM USERS WHERE AGE > 18 GROUP BY AGE ORDER BY AGE ASC;