SELECT USER_ID,NAMEUSER,AGE,
CASE
    WHEN AGE >= 17 THEN 'ES MAYOR DE EDAD'
    ELSE 'NO ES MAYOR DE EDAD'
END AS ageText
FROM USERS;


SELECT USER_ID,NAMEUSER,AGE,
CASE
    WHEN AGE >= 17 THEN TRUE
    ELSE 'NO ES MAYOR DE EDAD'
END AS ageText
FROM USERS;